spring:
  application:
    name: reactive-rest-api

  r2dbc:
#    url: jdbc:postgresql://localhost:5432/reactive-rest-api
    url: r2dbc:postgresql://localhost:5432/reactive-rest-api
    username: postgres
    password: root

server:
  port: 9999

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger-ui.html
